### ISSUE TITLE
Error while receiving a control message (SocketClosed): received exception "read of closed file"

### ISSUE THREAD

**Issue by adolfaka** [dperson/torproxy#46]
I use [TorIpChanger](https://github.com/DusanMadar/TorIpChanger) in [Celery](http://www.celeryproject.org) tasks, which is packaged in a Docker container together with **torproxy**, which is also packaged in a container and sometimes get an exception `[2020-04-27 16: 41: 33,189: ERROR / ForkPoolWorker-2] Task api.resources.main.initialize [5c2122a8-0d73-4db4-b461-1ffd533064ca] raised unexpected: TorIpError ('Failed to obtain a new usable Tor IP')`

```
[2020-04-27 16:41:25,476: DEBUG/ForkPoolWorker-2] GETCONF __owningcontrollerprocess (runtime: 0.0007)
[2020-04-27 16:41:25,478: INFO/ForkPoolWorker-2] Error while receiving a control message (SocketClosed): received exception "read of closed file"
[2020-04-27 16:41:26,303: DEBUG/ForkPoolWorker-2] GETCONF __owningcontrollerprocess (runtime: 0.0006)
[2020-04-27 16:41:26,304: INFO/ForkPoolWorker-2] Error while receiving a control message (SocketClosed): received exception "read of closed file"
[2020-04-27 16:41:27,146: DEBUG/ForkPoolWorker-2] GETCONF __owningcontrollerprocess (runtime: 0.0007)
[2020-04-27 16:41:27,148: INFO/ForkPoolWorker-2] Error while receiving a control message (SocketClosed): received exception "read of closed file"
[2020-04-27 16:41:27,932: DEBUG/ForkPoolWorker-2] GETCONF __owningcontrollerprocess (runtime: 0.0008)
[2020-04-27 16:41:27,934: INFO/ForkPoolWorker-2] Error while receiving a control message (SocketClosed): received exception "read of closed file"
[2020-04-27 16:41:28,708: DEBUG/ForkPoolWorker-2] GETCONF __owningcontrollerprocess (runtime: 0.0012)
[2020-04-27 16:41:28,742: INFO/ForkPoolWorker-2] Error while receiving a control message (SocketClosed): received exception "read of closed file"
[2020-04-27 16:41:29,563: DEBUG/ForkPoolWorker-2] GETCONF __owningcontrollerprocess (runtime: 0.0007)
[2020-04-27 16:41:29,565: INFO/ForkPoolWorker-2] Error while receiving a control message (SocketClosed): received exception "read of closed file"
[2020-04-27 16:41:30,354: DEBUG/ForkPoolWorker-2] GETCONF __owningcontrollerprocess (runtime: 0.0009)
[2020-04-27 16:41:30,356: INFO/ForkPoolWorker-2] Error while receiving a control message (SocketClosed): received exception "read of closed file"
[2020-04-27 16:41:30,356: INFO/ForkPoolWorker-2] Error while receiving a control message (SocketClosed): received exception "peek of closed file"
[2020-04-27 16:41:30,357: INFO/ForkPoolWorker-2] Error while receiving a control message (SocketClosed): received exception "peek of closed file"
[2020-04-27 16:41:30,357: INFO/ForkPoolWorker-2] Error while receiving a control message (SocketClosed): received exception "peek of closed file"
[2020-04-27 16:41:30,357: INFO/ForkPoolWorker-2] Error while receiving a control message (SocketClosed): received exception "peek of closed file"
[2020-04-27 16:41:30,357: INFO/ForkPoolWorker-2] Error while receiving a control message (SocketClosed): received exception "peek of closed file"
[2020-04-27 16:41:30,357: INFO/ForkPoolWorker-2] Error while receiving a control message (SocketClosed): received exception "peek of closed file"
[2020-04-27 16:41:30,358: INFO/ForkPoolWorker-2] Error while receiving a control message (SocketClosed): received exception "peek of closed file"
[2020-04-27 16:41:30,358: INFO/ForkPoolWorker-2] Error while receiving a control message (SocketClosed): received exception "peek of closed file"
[2020-04-27 16:41:30,358: INFO/ForkPoolWorker-2] Error while receiving a control message (SocketClosed): received exception "peek of closed file"
[2020-04-27 16:41:30,358: INFO/ForkPoolWorker-2] Error while receiving a control message (SocketClosed): received exception "peek of closed file"
[2020-04-27 16:41:30,359: INFO/ForkPoolWorker-2] Error while receiving a control message (SocketClosed): received exception "peek of closed file"
[2020-04-27 16:41:30,359: INFO/ForkPoolWorker-2] Error while receiving a control message (SocketClosed): received exception "peek of closed file"
[2020-04-27 16:41:30,359: INFO/ForkPoolWorker-2] Error while receiving a control message (SocketClosed): received exception "peek of closed file"
[2020-04-27 16:41:30,359: INFO/ForkPoolWorker-2] Error while receiving a control message (SocketClosed): received exception "peek of closed file"
[2020-04-27 16:41:30,359: INFO/ForkPoolWorker-2] Error while receiving a control message (SocketClosed): received exception "peek of closed file"
[2020-04-27 16:41:30,360: INFO/ForkPoolWorker-2] Error while receiving a control message (SocketClosed): received exception "peek of closed file"
[2020-04-27 16:41:30,360: INFO/ForkPoolWorker-2] Error while receiving a control message (SocketClosed): received exception "peek of closed file"
[2020-04-27 16:41:30,360: INFO/ForkPoolWorker-2] Error while receiving a control message (SocketClosed): received exception "peek of closed file"
[2020-04-27 16:41:31,150: DEBUG/ForkPoolWorker-2] GETCONF __owningcontrollerprocess (runtime: 0.0006)
[2020-04-27 16:41:31,151: INFO/ForkPoolWorker-2] Error while receiving a control message (SocketClosed): received exception "read of closed file"
[2020-04-27 16:41:31,913: DEBUG/ForkPoolWorker-2] GETCONF __owningcontrollerprocess (runtime: 0.0007)
[2020-04-27 16:41:31,914: INFO/ForkPoolWorker-2] Error while receiving a control message (SocketClosed): received exception "read of closed file"
[2020-04-27 16:41:32,680: DEBUG/ForkPoolWorker-2] GETCONF __owningcontrollerprocess (runtime: 0.0008)
[2020-04-27 16:41:32,682: INFO/ForkPoolWorker-2] Error while receiving a control message (SocketClosed): received exception "read of closed file"
```

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 650, in __protected_call__
    return self.run(*args, **kwargs)
  File "/app/api/errors.py", line 131, in wrapped
    current_ip = tor_ip_changer.get_new_ip()
  File "/usr/local/lib/python3.7/site-packages/toripchanger/changer.py", line 113, in get_new_ip
    raise TorIpError("Failed to obtain a new usable Tor IP")
toripchanger.exceptions.TorIpError: Failed to obtain a new usable Tor IP
```

> python -V
> Python 3.7.6

> uname -a
> Linux 93a9f4b2cd04 4.19.75 #1 SMP PREEMPT Mon Mar 23 11:23:28 UTC 2020 aarch64 GNU/Linux

> toripchanger==1.1.3

**Comment by dperson** [comment]
If the `TorIpChanger` container is throwing errors, why are you sending them to me? That's not a container that I created or maintain?

**Comment by adolfaka** [comment]
I acknowledge that you are not a developer and do not support TorIpChanger. The first listing says that I have an explicit relation to torproxy, IE: `[2020-04-27 16:41:25,476: DEBUG/ForkPoolWorker-2] GETCONF __owningcontrollerprocess (runtime: 0.0007)
[2020-04-27 16:41:25,478: INFO/ForkPoolWorker-2] Error while receiving a control message (SocketClosed): received exception "read of closed file" `
